version: "3"

services:
  server:
    env_file:
      - .env.development
    volumes:
      - ./server:/app
      - ./server/node_modules:/app/node_modules
    command: ["npm", "run", "dev"]
volumes:
  container_node_modules:
